[package]
name = "c2pa-node"
version = "0.1.0"
license = "MIT"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
async-trait = "0.1.77"
ciborium = "0.2.2"
#c2pa = { version = "0.49", features = ["file_io", "pdf"] }
c2pa = { path = "../c2pa-rs/sdk", features = ["file_io", "pdf"] }
futures = "0.3"
neon = { version = "1.0.0", default-features = false, features = [
    "futures",
    "napi-6",
] }
neon-serde4 = "1.0.0"
pem = "3.0.4"
reqwest = { version = "0.12.2", features = [
    "blocking",
    "brotli",
    "deflate",
    "gzip",
] }
serde = { version = "1.0.203", features = ["derive"] }
serde_bytes = "0.11.15"
serde_json = "1.0.117"
thiserror = "1.0.61"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
tokio-util = "0.7.13"
